from typing import Any, Protocol, List


class IDBMetadata(Protocol):

    def get_tables(self) -> List[Any]: ...

    def get_columns(self, table) -> List[Any]: ...

    def get_instances(self, table, offset: int,
                      page_size: int) -> List[Any]: ...

    def get_column_key(self, column) -> str: ...

    def get_column_value(self, column_key, record) -> Any: ...

    def column_is_foreign_key(self, column) -> bool: ...

    def get_table_name(self, table) -> str: ...

    def get_record_id(self, record) -> int: ...
