from typing import Any, Protocol, List


class IDBMetadata(Protocol):

    def get_tables(self) -> List[Any]: ...

    def get_table_columns_from_table(self, table) -> List[Any]: ...

    def get_table_columns_from_record(self, record) -> List[Any]: ...

    def get_records(self, table, offset: int, page_size: int) -> List[Any]: ...

    def get_column_name(self, column) -> str: ...

    def get_field_value(self, column_name, record) -> Any: ...

    def column_is_foreign_key(self, column) -> bool: ...

    def get_table_name_from_table(self, table) -> str: ...

    def get_table_name_from_record(self, record) -> str: ...

    def get_record_id(self, record) -> int: ...

    def get_related_records(self, record) -> List[Any]: ...
